prefix c: <http://orkg.org/orkg/class/>
prefix r: <http://orkg.org/orkg/resource/>

prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?property ?label
where {
  ?subject ?property ?object.
  ?property rdfs:label ?label.
}
